### ISSUE TITLE
Program data wraps incorrectly for some programs

### ISSUE THREAD

**Issue by hornc** [hornc/abctag#7]
See https://github.com/hornc/CTBASIC/issues/6

Program triggering the issue ([ABCT compiled version of this](https://github.com/hornc/CTBASIC/blob/graphics/examples/ANIMTEST001.bas)):

```
2725982173686371546601146872886478949676848343266687991455439775039246418566991564641072288886220641561220670417516878231337933182184221424474093486845123125288670924515227783347655713180738218612886808832567033405941261870209198197499335522520203793089647883525078726559522656322780833408305628209269451473841003952210357194804200927150864610020756488192140187415701229030023952457438960925517992085597157234115289733115229439541089867784618086421793464268100833257701933775660453143156550120230674427663139648925188894161008175666402137753021069691834098297645921724202153242602931770834033441974631172949352571451809476181649397847949984029722320500590490703749618295737914214793876366690181800306882307438513493238780477058778118173082607282107530831688589902108332787303323549563264682736128778696218029374094176060567774168320432597567000188014389411028017637004562908145413670119998291596935662982757593568414959308475684205073026516105003125317845476108577246127248204080999031261611309305491371624651666947921800000150020852464221004167616123654694382655473799426045366673852202654542189718580937791357707916724009533567448290513254034560106021425092655860067769504879958
```

**Expect:**
The cyclic tag version of the program should rotate by one CT symbol every step. The leftmost symbol in the string should appear in the rightmost position of the string in the following step.

Expected CT symbols at numbered steps:

```
...
   465	00111010010111001000 ... 10100010110000101011
   466	01110100101110010000 ... 01000101100001010110
   467	11101001011100100000 ... 10001011000010101100
   468	11010010111001000000 ... 00010110000101011001
   469	10100101110010000001 ... 00101100001010110011
   470	01001011100100000011 ... 01011000010101100111
   471	10010111001000000110 ... 10110000101011001110
   472	00101110010000001101 ... 01100001010110011101
   473	0101110010000001101; ... 11000010101100111010
   474	101110010000001101;; ... 10000101011001110100
   475	01110010000001101;;; ... 00001010110011101001
   476	1110010000001101;;;; ... 00010101100111010010
   477	110010000001101;;;;; ... 00101011001110100101
   478	10010000001101;;;;;; ... 01010110011101001011
   479	0010000001101;;;;;;; ... 10101100111010010111
   480	010000001101;;;;;;;; ... 01011001110100101110
   481	10000001101;;;;;;;;; ... 10110011101001011100
   482	0000001101;;;;;;;;;; ... 01100111010010111001
   483	000001101;;;;;;;;;;; ... 11001110100101110010
   484	00001101;;;;;;;;;;;; ... 10011101001011100100
   485	0001101;;;;;;;;;;;;; ... 00111010010111001000
   486	001101;;;;;;;;;;;;;; ... 01110100101110010000
   487	01101;;;;;;;;;;;;;;; ... 11101001011100100000
   488	1101;;;;;;;;;;;;;;;; ... 11010010111001000000
   489	101;;;;;;;;;;;;;;;;; ... 10100101110010000001
   490	01;;;;;;;;;;;;;;;;;; ... 01001011100100000011
   491	1;;;;;;;;;;;;;;;;;;; ... 10010111001000000110
   492	;;;;;;;;;;;;;;;;;;;; ... 00101110010000001101
   493	;;;;;;;;;;;;;;;;;;;; ... 0101110010000001101;
   494	;;;;;;;;;;;;;;;;;;;; ... 101110010000001101;;
   495	;;;;;;;;;;;;;;;;;;;; ... 01110010000001101;;;
   496	;;;;;;;;;;;;;;;;;;;; ... 1110010000001101;;;;
   497	;;;;;;;;;;;;;;;;;;;; ... 110010000001101;;;;;
   498	;;;;;;;;;;;;;;;;;;;; ... 10010000001101;;;;;;
   499	;;;;;;;;;;;;;;;;;;;; ... 0010000001101;;;;;;;
   500	;;;;;;;;;;;;;;;;;;;; ... 010000001101;;;;;;;;
   501	;;;;;;;;;;;;;;;;;;;; ... 10000001101;;;;;;;;;
   502	;;;;;;;;;;;;;;;;;;;; ... 0000001101;;;;;;;;;;
   503	;;;;;;;;;;;;;;;;;;;; ... 000001101;;;;;;;;;;;
   504	;;;;;;;;;;;;;;;;;;;; ... 00001101;;;;;;;;;;;;
   505	;;;;;;;;;;;;;;;;;;;; ... 0001101;;;;;;;;;;;;;
   506	;;;;;;;;;;;;;;;;;;;; ... 001101;;;;;;;;;;;;;;
   507	;;;;;;;;;;;;;;;;;;;; ... 01101;;;;;;;;;;;;;;;
   508	;;;;;;;;;;;;;;;;;;;; ... 1101;;;;;;;;;;;;;;;;
   509	;;;;;;;;;;;;;;;;;;;; ... 101;;;;;;;;;;;;;;;;;
   510	;;;;;;;;;;;;;;;;;;;; ... 01;;;;;;;;;;;;;;;;;;
   511	;;;;;;;;;;;;;;;;;;;; ... 1;;;;;;;;;;;;;;;;;;;
   512	;;;;;;;;;;;;;;;;;;;; ... ;;;;;;;;;;;;;;;;;;;;
   513	;;;;;;;;;;;;;;;;;;;; ... ;;;;;;;;;;;;;;;;;;;;
   514	;;;;;;;;;;;;;;;;;;;; ... ;;;;;;;;;;;;;;;;;;;;
   515	;;;;;;;;;;;;;;;;;;;; ... ;;;;;;;;;;;;;;;;;;;;
   516	;;;;;;;;;;;;;;;;;;;; ... ;;;;;;;;;;;;;;;;;;;;
   517	;;;;;;;;;;;;;;;;;;;; ... ;;;;;;;;;;;;;;;;;;;;
   518	;;;;;;;;;;;;;;;;;;;; ... ;;;;;;;;;;;;;;;;;;;;
   519	;;;;;;;;;;;;;;;;;;;; ... ;;;;;;;;;;;;;;;;;;;;
   520	;;;;;;;;;;;;;;;;;;;; ... ;;;;;;;;;;;;;;;;;;;;
   521	;;;;;;;;;;;;;;;;;;;; ... ;;;;;;;;;;;;;;;;;;;;
   522	;;;;;;;;;;;;;;;;;;;; ... ;;;;;;;;;;;;;;;;;;;;
   523	;;;;;;;;;;;;;;;;;;;; ... ;;;;;;;;;;;;;;;;;;;;
   524	;;;;;;;;;;;;;;;;;;;; ... ;;;;;;;;;;;;;;;;;;;;
   525	;;;;;;;;;;;;;;;;;;;; ... ;;;;;;;;;;;;;;;;;;;;
   526	;;;;;;;;;;;;;;;;;;;; ... ;;;;;;;;;;;;;;;;;;;;
   527	;;;;;;;;;;;;;;;;;;;; ... ;;;;;;;;;;;;;;;;;;;;
   528	;;;;;;;;;;;;;;;;;;;; ... ;;;;;;;;;;;;;;;;;;;;
   529	;;;;;;;;;;;;;;;;;;;; ... ;;;;;;;;;;;;;;;;;;;;
   530	;;;;;;;;;;;;;;;;;;;; ... ;;;;;;;;;;;;;;;;;;;;
   531	;;;;;;;;;;;;;;;;;;;; ... ;;;;;;;;;;;;;;;;;;;;
   532	;;;;;;;;;;;;;;;;;;;; ... ;;;;;;;;;;;;;;;;;;;;
   533	;;;;;;;;;;;;;;;;;;;; ... ;;;;;;;;;;;;;;;;;;;;
   534	;;;;;;;;;;;;;;;;;;;; ... ;;;;;;;;;;;;;;;;;;;;
   535	;;;;;;;;;;;;;;;;;;;; ... ;;;;;;;;;;;;;;;;;;;;
   536	;;;;;;;;;;;;;;;;;;;; ... ;;;;;;;;;;;;;;;;;;;;
   537	;;;;;;;;;;;;;;;;;;;; ... ;;;;;;;;;;;;;;;;;;;;
   538	;;;;;;;;;;;;;;;;;;;; ... ;;;;;;;;;;;;;;;;;;;;
   539	;;;;;;;;;;;;;;;;;;;; ... ;;;;;;;;;;;;;;;;;;;;
   540	;;;;;;;;;;;;;;;;;;;; ... ;;;;;;;;;;;;;;;;;;;;
```
Generated using :
```
./ct.py -d <(./CTBASIC.py examples/ANIMTEST001.bas -tCT) 1 | head -n540 | sed 's/^\(.\{20\}\).*\(.\{20\}\)/\1 ... \2/' | nl
```

**Actual:** CT symbols:

```
...
   465	00111010010111001000 ... 10100010110000101011
   466	01110100101110010000 ... 01000101100001010110
   467	11101001011100100000 ... 10001011000010101100
   468	11010010111001000000 ... 00010110000101011001
   469	10100101110010000001 ... 00101100001010110011
   470	01001011100100000011 ... 01011000010101100111
   471	10010111001000000110 ... 10110000101011001110
   472	00101110010000001101 ... 01100001010110011101
   473	0101110010000001101; ... 11000010101100111010
   474	101110010000001101;; ... 10000101011001110100
   475	01110010000001101;;; ... 00001010110011101001
   476	1110010000001101;;;; ... 00010101100111010010
   477	110010000001101;;;;; ... 00101011001110100101
   478	10010000001101;;;;;; ... 01010110011101001011
   479	0010000001101;;;;;;; ... 10101100111010010111
   480	010000001101;;;;;;;; ... 01011001110100101110
   481	10000001101;;;;;;;;; ... 10110011101001011100
   482	0000001101;;;;;;;;;; ... 01100111010010111001
   483	000001101;;;;;;;;;;; ... 11001110100101110010
   484	00001101;;;;;;;;;;;; ... 10011101001011100100
   485	0001101;;;;;;;;;;;;; ... 00111010010111001000
   486	001101;;;;;;;;;;;;;; ... 01110100101110010000
   487	01101;;;;;;;;;;;;;;; ... 11101001011100100000
   488	1101;;;;;;;;;;;;;;;; ... 11010010111001000000
   489	101;;;;;;;;;;;;;;;;; ... 10100101110010000001
   490	01;;;;;;;;;;;;;;;;;; ... 01001011100100000011
   491	1;;;;;;;;;;;;;;;;;;; ... 10010111001000000110
   492	;;;;;;;;;;;;;;;;;;;; ... 00101110010000001101
   493	;;;;;;;;;;;;;;;;;;;; ... 0101110010000001101;
   494	;;;;;;;;;;;;;;;;;;;; ... 101110010000001101;;
   495	;;;;;;;;;;;;;;;;;;;; ... 01110010000001101;;;
   496	;;;;;;;;;;;;;;;;;;;; ... 1110010000001101;;;;
   497	;;;;;;;;;;;;;;;;;;;; ... 110010000001101;;;;;
   498	;;;;;;;;;;;;;;;;;;;; ... 10010000001101;;;;;;
   499	;;;;;;;;;;;;;;;;;;;; ... 0010000001101;;;;;;;
   500	;;;;;;;;;;;;;;;;;;;; ... 010000001101;;;;;;;;
   501	;;;;;;;;;;;;;;;;;;;; ... 10000001101;;;;;;;;;
   502	;;;;;;;;;;;;;;;;;;;; ... 0000001101;;;;;;;;;;
   503	;;;;;;;;;;;;;;;;;;;; ... 000001101;;;;;;;;;;;
   504	;;;;;;;;;;;;;;;;;;;; ... 00001101;;;;;;;;;;;;
   505	;;;;;;;;;;;;;;;;;;;; ... 0001101;;;;;;;;;;;;;
   506	;;;;;;;;;;;;;;;;;;;; ... 001101;;;;;;;;;;;;;;
   507	;;;;;;;;;;;;;;;;;;;; ... 01101;;;;;;;;;;;;;;;
   508	;;;;;;;;;;;;;;;;;;;; ... 1101;;;;;;;;;;;;;;;;
   509	;;;;;;;;;;;;;;;;;;;; ... 101;;;;;;;;;;;;;;;;;
   510	;;;;;;;;;;;;;;;;;;;; ... 01;;;;;;;;;;;;;;;;;;
   511	;;;;;;;;;;;;;;;;;;;; ... 1;;;;;;;;;;;;;;;;;;;
   512	;;;;;;;;;;;;;;;;;;;; ... ;;;;;;;;;;;;;;;;;;;;
   513	;;;;;;;;;;;;;;;;;;;; ... ;;;;;;;;;;;;;;;;;;;;
   514	;;;;;;;;;;;;;;;;;;;; ... ;;;;;;;;;;;;;;;;;;;;
   515	;;;;;;;;;;;;;;;;;;;; ... ;;;;;;;;;;;;;;;;;;;;
   516	;;;;;;;;;;;;;;;;;;;; ... ;;;;;;;;;;;;;;;;;;;;
   517	;;;;;;;;;;;;;;;;;;;; ... ;;;;;;;;;;;;;;;;;;;;
   518	;;;;;;;;;;;;;;;;;;;; ... ;;;;;;;;;;;;;;;;;;;;
   519	;;;;;;;;;;;;;;;;;;;; ... ;;;;;;;;;;;;;;;;;;;;
   520	;;;;;;;;;;;;;;;;;;;; ... ;;;;;;;;;;;;;;;;;;;;
   521	;;;;;;;;;;;;;;;;;;;; ... ;;;;;;;;;;;;;;;;;;;;
   522	;;;;;;;;;;;;;;;;;;;; ... ;;;;;;;;;;;;;;;;;;;;
   523	;;;;;;;;;;;;;;;;;;;; ... ;;;;;;;;;;;;;;;;;;;;
   524	;;;;;;;;;;;;;;;;;;;; ... ;;;;;;;;;;;;;;;;;;;;
   525	;;;;;;;;;;;;;;;;;;;; ... ;;;;;;;;;;;;;;;;;;;;
   526	;;;;;;;;;;;;;;;;;;;; ... ;;;;;;;;;;;;;;;;;;;;
   527	;;;;;;;;;;;;;;;;;;;; ... ;;;;;;;;;;;;;;;;;;;;
   528	;;;;;;;;;;;;;;;;;;;; ... ;;;;;;;;;;;;;;;;;;;;
   529	;;;;;;;;;;;;;;;;;;;; ... ;;;;;;;;;;;;;;;;;;;;
   530	;;;;;;;;;;;;;;;;;;;; ... ;;;;;;;;;;;;;;;;;;;;
   531	;;;;;;;;;;;;;;;;;;;; ... ;;;;;;;;;;;;;;;;;;;;
   532	;;;;;;;;;;;;;;;;;;;; ... ;;;;;;;;;;;;;;;;;;;;
   533	;;;;;;;;;;;;;;;;;;;; ... ;;;;;;;;;;;;;;;;;;;;
   534	;;;;;;;;;;;;;;;;;;;; ... ;;;;;;;;;;;;;;;;;;;;
   535	;;;;;;;;;;;;;;;;;;;; ... ;;;;;;;;;;;;;;;;;;;;
   536	;;;;;;;;;;;;;;;;;;;; ... ;;;;;;;;;;;;;;;;;;;;
   537	;;;;;;;;;;;;;;;;;;;; ... ;;;;;;;;;;;;;;;;;;;1
   538	;;;;;;;;;;;;;;;;;;;; ... ;;;;;;;;;;;;;;;;;;;0
   539	;;;;;;;;;;;;;;;;;;;; ... ;;;;;;;;;;;;;;;;;;0;
   540	;;;;;;;;;;;;;;;;;;;; ... ;;;;;;;;;;;;;;;;;0;;
```

Generated using:
```
../abct/abct-cli $(./CTBASIC.py examples/ANIMTEST001.bas -tABCT) 2  | cut -f1 | sed 's/11/a/g;s/10/b/g;s/0/;/g;s/a/1/g;s/b/0/g' | head -n540 | sed 's/^\(.\{20\}\).*\(.\{20\}\)/\1 ... \2/' | nl
```

At step 537 a `1` appears on the right from nowhere, then flips to a `0` in the next step -- this demonstrates the ABCT program changing when it shouldn't.

Perhaps due to a rounding error, or overflow somewhere? There doesn't seem to be anything special about that position in the CT program; it's in a large block of `;` (delete) symbols.

**TODO**
* Get the ABCT program value at step 536 (correct)
* Figure out how it is currently processed by `pn()` https://github.com/hornc/abctag/blob/2e683561362936cc09406724277c739a42c014b1/abct/abct.py#L5
* Figure what the correct result should be and why it isn't produced.

**Comment by hornc** [comment]
Program value at step 536 (correct):
```
2725982173685425276620178397279307998851884070158300554239720336131937368724833951875320824584953926553206247460060147566788342053452031392489447098664223409601499605760691500979814804852452294813332934871682777717440012604135573142987196202112707261254571527760142839652870866844777706693514440500017671257209361839008928857812767283591624745973022302503580058980076600705501735794806473778453496839693635020991608425460984358922052657494592211492355931185314092022330208774805259815793655375764676391820677299295550367549221941527385999558503019117051983611405999262442358095809182117652660566073394529066040732687813771810642457024729371513754745954008848364925749032305571547150529117587957688094498193660933172533842346405558765154208913802053373143114121021096100067735235541952351408453196253632102645073995281338773043126278004641939481235178170050137221821763361669759489263909104106154538407152334790740820817762099719064668899100713042542989073950722750355152073706976825537896950216651457969265604134639875960282782820266632408939619656250933120364930447979882396034315491833611255012603524885800888695231733579544444217845673146837150853025121768450528089528724357119
```

Program value at 537 (incorrect):

```
2044486630264035162108339492884597928799686293664861883525538726911223423001443229245008550872098505026559410114926807249742010063183612913062582710693170902618902374837946982086941352877946076706085347279395790656434025815818889092712092609824160608584181704982833035367262995505002587939120934189744086195560840647061246204942042443701077280783945534257993273318842758890397178089318530301850300234043903517632178322581064631775478163233486512056848619312737530638437931293040881703782264262395873318596682741873718787019013461935354033712677508759825714545544630944922815780875002743907512788408431518909217991893617010123389068562792268805242242588243656202879098183177475708864312823260231483324917444215200901681703933108662620339080194981156511776550517354715927416442095855341108469267627937373170333590835092715135489637871037377833774178540308895139645629112716865664699671129439918237286979741019627563033848186444279198094706897488812774460846038658456093521132658324929315976315227669759722185359872843572356468254389262243383224623222660570237143210225048176851404450270108451878918748838885026129251863212504534509176454985649453946809558442556342883867903809028095
```

Using the step 537 CT program from the output of [ct.py](https://github.com/hornc/CTBASIC/blob/graphics/ct.py) and converting it to ABCT using https://github.com/hornc/CTBASIC/blob/graphics/CTBASIC.py#L199

The expected program value at step 537 should be:
```
2725982173685357685906589787129541858173430552250573489931217285756478161640469482552356689451720046776515696499823540716089849099641210129880441872054230100437054946795548213683975303329666006005504227122950192454148045329569991613930587118591967586541077646085594650908090557587616322531484648129479336762517000374618027980977701245606342188581379917264196517147647217428043488281233823714473852048240989524768552432431637084089929997719676918367519273032818015265710758198679133499667700836909408441283026834099662390263415953107015067646103507961125437285386262258624452513845414428988695293780165773285415617443327134341456908613219851853607112199482888223295321850202165644153361087726484122602585791599935217096486693014545858101055933061286336981543974198883804799016573939706041234308657747930289344644672544760884457712603072434697807739491532765210680347343752896449654710304327783397304755905871859755657287491838698863854964244621104277427155101955537009466228463161445863004155347013790459737917678367206732795117368391170561979436617195673914103955226106412504791742794300098130331195915327151814156110558219296796243987134725489318192604324228460503691043255877631
```

The actual value is exactly 2**3916 less than expected...

There's a problem with the function that rotates the bijective base2 program string by one (`1` - delete) or two (`2?` append ) symbols. Looks like it is triggering in this case when the current symbol `n()` is `1`, which is the simpler of the two rotations.
https://github.com/hornc/abctag/blob/master/abct/abct.py#L4

**Comment by hornc** [comment]
New lowest discovered program value found which triggers this bug:

2**48 - 2 = 281474976710654

`bct(281474976710654)`
'11111111111111111111111111111111111111111111111'

`bct(r(281474976710654))`
'111111111111111111111111111111111111111111111110'

^^^ adds an extra zero instead of rotating the string by one.

This is an example of a correct rotation, which occurs for all `2**n - 2` for `n < 48`:
```
>>> bct(2**47 - 2)
'1111111111111111111111111111111111111111111111'
>>> bct(r(2**47 - 2))
'1111111111111111111111111111111111111111111111'
```

All `r(2**n - 2)` for `n >= 48` appear to trigger the bug.

Some other values clearly do too, but this form is a string of all BCT 1s greater than  length = 46.

**Comment by hornc** [comment]
The issue is that `s(x)`, a function which is supposed to return the number of digits (symbol length) in a bijective base2 numeral, sometimes doesn't return the correct count. It should match `len(bct(x))`.

The formula represented by the fn `s(x)` is correct.

The problem is with rounding in `math.log()`

```
from math import log

def pow2testlog(n):
    # Test rounding on math.log()
    assert log(2**n-1) != log(2**n)
```

```
>>> pow2testlog(2)
>>> pow2testlog(20)
>>> pow2testlog(45)
>>> pow2testlog(46)
>>> pow2testlog(47)
>>> pow2testlog(48)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in pow2testlog
AssertionError
```
Anything over `2**48` rounds in a way that does not distinguish between the log of `2**n` and `2**n-1`.
